bootswatch: lumen

slogan: "hmhv's blog"

menu:
  - title: Archives
    url: archives
    intro: "Archives"
    icon: "fa fa-archive"
  - title: Apps
    url: apps
    intro: "app gallery"
    icon: "fa fa-cubes"
  - title: More
    intro: "infomation"
    icon: "fa fa-info-circle"
    dropdown: true
    submenu:
    - title: "Privacy Policy"
      url: privacy
      intro: "Privacy Policy"
      icon: "fa fa-lock"
    - title: "About me"
      url: aboutme
      intro: "About me"
      icon: "fa fa-user"
    - title: "Qiita"
      fullurl: true
      url: "http://qiita.com/hongmhoon"
      intro: "Qiita"
      icon: "fa fa-circle-o"
    - title: "github"
      fullurl: true
      url: "https://github.com/hmhv"
      intro: "github"
      icon: "fa fa-github"
    - title: Linkedin
      fullurl: true
      url: "http://jp.linkedin.com/in/hongmhoon"
      intro: Linkedin
      icon: "fa fa-linkedin-square"
    - title: Contact
      fullurl: true
      url: "mailto:admin@hmhv.info"
      intro: "Contact"
      icon: "fa fa-paper-plane"

apps:
  - title: "MP3 Folders"
    url: /apps/mp3folders/
    intro: "MP3 Folders"
    image: "/images/mp3folders.png"
  - title: "Ready Tweet 2"
    url: /apps/readytweet2/
    intro: "Ready Tweet 2"
    image: "/images/readytweet.png"
  - title: "Cocoa Stars"
    url: /apps/ioscontrols/
    intro: "Cocoa Stars"
    image: "/images/ioscontrols.png"
  - title: "iRanKing"
    url: /apps/iranking/
    intro: "iRanKing"
    image: "/images/iranking.png"
  - title: "MagicBlue"
    url: /apps/magicblue/
    intro: "MagicBlue"
    image: "/images/magicblue.png"
  - title: "ヤマスキ"
    url: /apps/yamasuki/
    intro: "ヤマスキ"
    image: "/images/yamasuki.png"
  - title: "毎日イベント"
    url: /apps/eventviewer/
    intro: "毎日イベント"
    image: "/images/eventviewer.png"
  - title: "Pass Photo"
    url: /apps/passphoto/
    intro: "Pass Photo"
    image: "/images/passphoto.png"
  - title: "0=零"
    url: /apps/kanjinumerals/
    intro: "0=零"
    image: "/images/kanjinumerals.png"

support:
  - title: "KidsNote"
    url: http://www.kidsnote.com/
    intro: "KidsNote"
    image: "/images/kidsnote.jpeg"
  - title: "sweetie"
    url: http://sweetieapp.com/
    intro: "sweetie"
    image: "/images/sweetie.png"
  - title: "HiNative"
    url: http://hinative.com/
    intro: "HiNative"
    image: "/images/hinative.png"

widgets:
- tagcloud
- recent_posts
- apps
- support

rss: false
fancybox: false
favicon: favicon.ico
google_analytics: UA-40299127-1
